[project]
name = "nb_introspect"
version = "0.2.0"
dependencies = [
    'importlib-metadata; python_version<"3.8"',
]

[tool.setuptools.packages.find]
where = ["nb_introspect"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
