[project]
name = "nb_introspect"
version = "0.1.0"
dependencies = [
    'importlib-metadata; python_version<"3.8"',
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
 